// This file was generated by counterfeiter
package fakes

import (
	"sync"
	"time"

	"github.com/concourse/turbine/scheduler"
)

type FakeClock struct {
	CurrentTimeStub        func() time.Time
	currentTimeMutex       sync.RWMutex
	currentTimeArgsForCall []struct{}
	currentTimeReturns     struct {
		result1 time.Time
	}
}

func (fake *FakeClock) CurrentTime() time.Time {
	fake.currentTimeMutex.Lock()
	fake.currentTimeArgsForCall = append(fake.currentTimeArgsForCall, struct{}{})
	fake.currentTimeMutex.Unlock()
	if fake.CurrentTimeStub != nil {
		return fake.CurrentTimeStub()
	} else {
		return fake.currentTimeReturns.result1
	}
}

func (fake *FakeClock) CurrentTimeCallCount() int {
	fake.currentTimeMutex.RLock()
	defer fake.currentTimeMutex.RUnlock()
	return len(fake.currentTimeArgsForCall)
}

func (fake *FakeClock) CurrentTimeReturns(result1 time.Time) {
	fake.CurrentTimeStub = nil
	fake.currentTimeReturns = struct {
		result1 time.Time
	}{result1}
}

var _ scheduler.Clock = new(FakeClock)
